version: '3.2'

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

services:
  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - database:/var/lib/mysql

  http:
    image: nginx:1-alpine
    expose:
      - "80"
      - "443"
    depends_on:
    - php
    volumes:
    - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./public/:/srv/public/
    networks:
      - default
      - nginx-proxy

  php:
    build:
      context: ./.docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/
    tty: true

  node:
      build:
          context: ./.docker/node
      working_dir: /srv
      volumes:
          - ./:/srv/

volumes:
  database: ~
