version: '3.2'

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

services:
  http:
    environment:
      - VIRTUAL_HOST=simple-web.test
      - XDEBUG_CONFIG=idekey=remote-debug remote_host=192.168.72.1
