version: '3.2'

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

services:
  http:
    image: nginx:1-alpine
    expose:
      - "80"
      - "443"
    depends_on:
    - php
    volumes:
    - ./.docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./:/srv/public/
    networks:
      - default
      - nginx-proxy
  node:
      build:
          context: ./.docker/node
      working_dir: /srv
      volumes:
          - ./:/srv/

volumes:
  database: ~
